### ISSUE TITLE
Insall script on mac os x

### ISSUE THREAD

**Issue by georgid** [marl/massage#6]
I was looking for a fast implementation of pYIN in python and came across this repo. I need to install it on Mac OS X. I see that you have a travis.yml install file for linux only. 

I tried with `python3 setup.py install` but it seems PyPI does not know about medley:
```
error: Could not find suitable distribution for Requirement.parse('medleydb>=1.3.3')
```

Have you tried installing it on Mac so far? 
Do you have any instructions? 
Thanks!

**Comment by justinsalamon** [comment]
This repo is mostly skeleton code with many missing implementations. It's not ready for use. For pYIN I'd recommend using the C++ vamp implementation, which you can call from python using the vampy python module. Or you could use [CREPE](https://github.com/marl/crepe) ;)
